language: php
php: [5.6, 7.0, nightly, hhvm]
before_script:
    - composer selfupdate
    - composer require satooshi/php-coveralls ~1.0.0
    - composer install

script:
      - ./vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml

after_script:
      - php vendor/bin/coveralls -v
